"""empty message

Revision ID: 2a295a6d5feb
Revises: d693304e31b7
Create Date: 2022-02-08 16:52:29.915376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a295a6d5feb'
down_revision = 'd693304e31b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon_poke_master', sa.Column('poke_i', sa.Integer(), nullable=False))
    op.drop_constraint('pokemon_poke_master_poke_id_fkey', 'pokemon_poke_master', type_='foreignkey')
    op.create_foreign_key(None, 'pokemon_poke_master', 'pokemon', ['poke_i'], ['poke_id'])
    op.drop_column('pokemon_poke_master', 'poke_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon_poke_master', sa.Column('poke_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pokemon_poke_master', type_='foreignkey')
    op.create_foreign_key('pokemon_poke_master_poke_id_fkey', 'pokemon_poke_master', 'pokemon', ['poke_id'], ['poke_id'])
    op.drop_column('pokemon_poke_master', 'poke_i')
    # ### end Alembic commands ###
