"""empty message

Revision ID: 790dddd42f7f
Revises: ee12444abf66
Create Date: 2022-02-10 19:15:58.644608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790dddd42f7f'
down_revision = 'ee12444abf66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
